services:
  frontend:
    image: sechs-minuten-tagebuch/frontend
    container_name: sechs-minuten-tagebuch
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 62500:80
    depends_on:
      - backend

  backend:
    image: sechs-minuten-tagebuch/backend
    container_name: sechs-minuten-tagebuch-backend
    restart: unless-stopped
    user: 1000:1000
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 62501:81
    volumes:
      - ${DATA_PATH}:/app/data
