version: '3.9'

services:
  frontend:
    image: fuenf-minuten-tagebuch/frontend
    container_name: fuenf-minuten-tagebuch
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 62500:80
    depends_on:
      - backend
    networks:
      nginx:
    labels:
      - homepage.group=Social
      - homepage.name=5-Minuten Tagebuch
      - homepage.icon=mdi-book
      - homepage.href=https://5-minuten-tagebuch.marcelbruckner.info/
      - homepage.description=Unser digitales 5-Minuten Tagebuch

  backend:
    image: fuenf-minuten-tagebuch/api
    container_name: fuenf-minuten-tagebuch-api
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      USER_DATABASE_PATH: "data/db.sqlite"
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      APP_SECRET_KEY: '4352c9036368100cb0e7292aae9c0d10eee244b147a1a53148c2cfd19ecbd324'
    ports:
      - 62501:81
    volumes:
      - ./data:/app/data
    networks:
      nginx:

networks:
  nginx:  
    external: true
