version: '3.9'

services:
  frontend:
    image: sechs-minuten-tagebuch/frontend
    container_name: sechs-minuten-tagebuch
    build: 
      context: frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:4001
    ports:
      - 4000:80
    depends_on:
      - backend

  backend:
    image: sechs-minuten-tagebuch/backend
    container_name: sechs-minuten-tagebuch-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4001:81
    volumes:
      - ./data:/app/data