version: '3.9'

services:
  frontend:
    image: sechs-minuten-tagebuch/frontend
    container_name: sechs-minuten-tagebuch
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:4001
    ports:
      - 4000:80
    depends_on:
      - backend

  backend:
    image: sechs-minuten-tagebuch/backend
    container_name: sechs-minuten-tagebuch-backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      USER_DATABASE_PATH: "data/db.sqlite"
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      APP_SECRET_KEY: '4352c9036368100cb0e7292aae9c0d10eee244b147a1a53148c2cfd19ecbd324'
    ports:
      - 4001:81
    volumes:
      - ./data:/app/data
